name: API Testing

on:
  push:
    branches: [ main, develop, copilot/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

jobs:
  test-api:
    name: Test API Integration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check GitHub secret accessibility
        run: |
          echo "🔍 Checking GitHub secret accessibility..."
          if [ -z "$OPENROUTER_API_KEY" ]; then
            echo "❌ OPENROUTER_API_KEY GitHub secret is not accessible"
            echo "🔧 Please ensure the secret is properly configured in repository settings"
            exit 1
          else
            echo "✅ OPENROUTER_API_KEY GitHub secret is accessible"
            echo "🔑 Key length: ${#OPENROUTER_API_KEY} characters"
          fi
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        
      - name: Test API connection
        run: |
          echo "🌐 Testing API connection with GitHub secret..."
          npm run test:api
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        
      - name: Run Jest tests
        run: |
          echo "🧪 Running unit and integration tests..."
          npm run test:ci
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            coverage/
            *.log
          retention-days: 7